.prettierrc
Please include a summary of the change and a link to which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
=> no semicolons

.gitignore
Please include a summary of the change and a link to which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
=> update to ignore packge-lock

README.md
added Trello link as requested. firebase link already there
=> added Trello link to readme

README.md, package.json, src/App.js, src/LandingPage.js, yarn.lock
added logo to readme - started building landingpage component
- minor change
=> added logo to readme - started building landingpage component

.eslintrc, .gitignore, README.md, src/LandingPage.js
=> Improved google auth 🚀

.eslintrc, package.json, src/App.js, src/screens/SigninForm.js, yarn.lock
adding user email and password to the database model is not working
=> create user with email and logs in

src/App.js, src/pages/SigninForm.js
added phone number to database
Please include a summary of the change and a link to which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
used hooks
fixed phone number being in database
Please delete options that are not relevant.
manually tested it to makes sure it was being saved to data base and not being lost on refresh.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
see above
=> Jon palacio/fe

src/pages/ChooseYourContact.js
After users sign up, they are now able to add a contact (Loved One) and have that contact stored in an array on their user document in cloud firestore ☁️
=> store user's contact in db 🔥

src/components/SignInWithGoogle.js
added route to home from google sign in. auto push you to home page
Please include a summary of the change and a link to which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
=> Added Route to home page from sign in with google

src/App.js, src/components/Choose.js
=> Starting Point for Friday

.eslintrc, .travis.yml, src/App.js, src/components/AboutUs.js, src/components/NavBar.js, src/styles/AboutUs.js
yarn build not working trying npm run build instead doesnt affect package
=> Continuous deployment, Our Team, Basic Styling and Improvements

.travis.yml
=> CLI Should be working

src/App.js, src/components/DashBoard.js, src/components/ModalPhoneNumber.js, src/components/UpdateAccount.js
=> localStorage no longer stores stale values 😫

src/components/Login.js
quick change. had to remove border being used for styling.  sorry @blokboy
=> removed border using for styling

src/components/ChooseYourContact.js
Choose contact now checks to see if a user exists with the contact's email address before creating an account.
=> Added email check when selecting a new user

src/App.js, src/components/dashboard/ContactInfo.js, src/styles/ContactInfoPage.js, src/styles/Global.js
Pulls data from contact collection. Still needs option to update contact information.
=>  Basic ContactInfo.js page complete

src/components/DashMain.js, src/components/Footer.js, src/components/NavBar.js, src/components/dashboard/ScheduledContacts.js
=> Updated Nav mobile/desktop

src/components/DashMain.js, src/components/Footer.js, src/components/NavBar.js
=> Dashboard View Update

src/components/DashMain.js, src/components/dashboard/ScheduledContacts.js
=> Added Upcoming calls/Prev calls to dashboard

.eslintrc, src/components/DashMain.js, src/components/Footer.js, src/components/NavBar.js, src/components/UpdateAccount.js, src/components/dashboard/ScheduledContacts.js
Refactored styles with styled components for Desktop and Mobile views
=> UpdateAccount styling

src/App.js, src/components/ChooseCallPlan.js, src/components/ChooseYourContact.js, src/components/ContactInfo/ScheduledCall.js, src/components/DashMain.js, src/components/Footer.js, src/components/NavBar.js, src/components/ScheduleFreeCall.js, src/components/SchedulePaidCall.js, src/components/dashboard/Billing.js, src/components/dashboard/ContactInfo.js, src/components/dashboard/PreviousCalls.js, src/components/dashboard/ScheduledContacts.js, src/components/scheduler/Day.js, src/components/scheduler/Slot.js, src/components/scheduler/UpdateContact.js, src/components/scheduler/UpdateFreeCall.js, src/components/scheduler/UpdatePaidCall.js, src/styles/CallPlanView.js
Created components for both Billing and Updating Paid Calls
=> Billing Page & Update Paid Call Wireframes Complete

src/components/DashMain.js, src/components/Footer.js, src/components/UpdateAccount.js, src/components/dashboard/ScheduledContacts.js
Fixed the footer from being overlapped in some views.
Added styles for ScheduleContacts
Adjusted styles on the footer
adjusted styles on the navbar
- Checked on 4 different screen sizes
=> Update Account, Footer, Navbar, ScheduleContacts

src/components/AboutUs.js, src/components/DashMain.js, src/components/dashboard/PreviousCalls.js, src/components/dashboard/ScheduledContacts.js
adjusted deepgram log and hotdog is now sepperate from the links with updated styles
fixed logo link also
=> Updates to PrevCall + YourContact header/hotdog

src/components/CallConfirmation.js, src/components/DashMain.js, src/components/SchedulePaidCall.js, src/components/dashboard/ScheduledContacts.js, src/styles/Scheduler.js
Worked with Jon
updated styles on call confirmation page
=> Styled CallConfimation

src/components/DashMain.js, src/components/Landing/LandingPageMain.js, src/components/UpdateAccount.js, src/styles/LandingPageMain.js
=> tweaks to landing page

src/components/Auth/SignUp.js, src/components/SchedulePaidCall.js, src/styles/Form.js, src/styles/Scheduler.js
login/signing paddings added
updated paid call View
- Testing in my browser and different screen sizes
=> Adjusted suggested styling

src/components/Landing/LandingPageMain.js, src/styles/LandingPageMain.js
=> little tings on the landing page

src/components/DashMain.js, src/components/NavBar.js, src/components/SchedulePaidCall.js, src/components/dashboard/ScheduledContacts.js, src/components/scheduler/UpdatePaidCall.js, src/styles/LandingPageMain.js, src/styles/Scheduler.js, src/styles/UserCard/Img.js, src/styles/UserCard/User.js
=> removed hamburger and hot dogs

functions/tasks/caller.js, src/components/Auth/Login.js, src/components/DashMain.js, src/components/Loading.js, src/components/dashboard/CallRecord.js, src/components/dashboard/ContactInfo.js, src/components/dashboard/PreviousCalls.js, src/components/dashboard/ScheduledContacts.js, src/components/scheduler/UpdatePaidCall.js, src/styles/Scheduler.js
Both components are now sorted properly, and Upcoming Calls now shows calls scheduled by other people. Made some style updates as well.
=> Updated Upcoming Calls and Previous Calls

src/components/AboutUs.js
updated user profiles for the about us section
=> added in missing social account for Jon and I
